# docker-compose down --volumes
# docker-compose up --build

services:
    zookeeper:
        image: bitnami/zookeeper:latest
        ports:
            - 2181:2181
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

    kafka:
        image: bitnami/kafka:latest
        ports:
            - 9092:9092
            - 9093:9093
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT
            - KAFKA_CFG_LISTENERS=CLIENT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092
            - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
        depends_on:
            - zookeeper

    postgres:
        image: postgres
        container_name: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: bet_maker_db

    betmaker:
        build:
            context: ./bet_maker
            dockerfile: Dockerfile
        command: uvicorn app.run:app --reload --workers 1 --host 0.0.0.0 --port 8003
        ports:
            - 8080:8003
        volumes:
            - ./bet_maker:/usr/src/app
        environment:
            - KAFKA_HOST=kafka
            - KAFKA_PORT=9092
            - KAFKA_TOPICS=event-status
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=bet_maker_db
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
        depends_on:
            - kafka
            - zookeeper
            - postgres
    lineprovider:
        build:
            context: ./line_provider
            dockerfile: Dockerfile
        restart: always 
        command: uvicorn app.run:app --reload --workers 1 --host 0.0.0.0 --port 8002
        ports:
            - 8081:8002
        volumes:
            - ./line_provider:/usr/src/app
        environment:
            - KAFKA_HOST=kafka
            - KAFKA_PORT=9092
            - KAFKA_TOPICS=event-status
        depends_on:
            - kafka
            - zookeeper