# docker-compose down --volumes
# docker-compose up --build

services:
  zookeeper:
      image: bitnami/zookeeper:latest
      ports:
          - 2181:2181
      environment:
          - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
      image: bitnami/kafka:latest
      ports:
          - 9092:9092
          - 9093:9093
      environment:
          - KAFKA_BROKER_ID=1
          - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
          - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
          - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
          - ALLOW_PLAINTEXT_LISTENER=yes
          - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT
          - KAFKA_CFG_LISTENERS=CLIENT://:9092
          - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://localhost:9092
          - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      depends_on:
            - zookeeper
  # postgres:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: betting_system
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: